### ISSUE TITLE
-compatibility-version ld flag not compatible with OS X Tiger

### ISSUE THREAD

**Issue by mistydemeo** [cmatsuoka/libxmp#1]
libxmp 4.1.1 tries to link using the `-compatibility-version` flag, which isn't compatible with the `ld` that ships with OS X Tiger:

```
ld: unknown flag: -compatibility_version
collect2: ld returned 1 exit status
make: *** [lib/libxmp.4.1.1.dylib] Error 1
```

This isn't a critical issue because I can force a newer linker for users on Tiger, but that does add a slow-to-compile dependency. I don't mind if you're not interested in fixing this.

**Comment by cmatsuoka** [comment]
Is this still relevant? I'm closing this because it's an old issue, but please reopen if this is still a problem and we'll fix it.

**Comment by mistydemeo** [comment]
This is still relevant; sorry I never got around to submitting a patch.

**Comment by cmatsuoka** [comment]
Reopening issue. What's the best way to detect if we're building on OS X Tiger? I can add the detection to the configure script and change the Makefile to act accordingly.

**Comment by cmatsuoka** [comment]
Test for Tiger added in 2e2314e.
