### ISSUE TITLE
XMP-lite

### ISSUE THREAD

**Issue by mdahlgrengadd** [cmatsuoka/libxmp#140]
If I want libxmp-lite I compile everything but remove all loaders except .s3m .it .xm and .mod?

The "loaders" folder in xmp-lite directory only have mod... thats why I'm wondering.

https://github.com/cmatsuoka/libxmp/tree/master/lite/src/loaders

**Comment by carstene1ns** [comment]
The lite version gets some loaders from the normal version copied over (also the main header).
The mod loader is stripped down and supports fewer formats, so it is directly included.
You can generate a distribution archive with `Makefile.lite` from main directory.

**Comment by mdahlgrengadd** [comment]
Ok thanks
