### ISSUE TITLE
One of IMF files fails to be played

### ISSUE THREAD

**Issue by Wohlstand** [cmatsuoka/libxmp#142]
I have a small set of IMF files in a small ZIP archive: [IMF Files.zip](https://github.com/cmatsuoka/libxmp/files/3359280/IMF.Files.zip). All files are playing fine. However, `spaceintro.imf` fails to be open. At the same time, it works fine via MikMod. Can you check why it won't work on libXMP?

**Comment by sezero** [comment]
It fails here: https://github.com/cmatsuoka/libxmp/blob/master/src/loaders/imf_load.c#L453
Allowing 16 npt makes it play, e.g.:
```
diff --git a/src/loaders/imf_load.c b/src/loaders/imf_load.c
index e7eec29..b0c2aaf 100644
--- a/src/loaders/imf_load.c
+++ b/src/loaders/imf_load.c
@@ -450,7 +450,7 @@ static int imf_load(struct module_data *m, HIO_HANDLE *f, const int start)
        xxi->aei.flg |= ii.env[0].flg & 0x04 ?  XMP_ENVELOPE_LOOP : 0;
 
        /* Sanity check */
-       if (xxi->aei.npt >= 16) {
+       if (xxi->aei.npt > 16) {
            return -1;
        }
 
```
@cmatsuoka: Is this correct?

**Comment by Wohlstand** [comment]
Oh, interesting... I should verify this with all files I have on my end. :thinking:

**Comment by Wohlstand** [comment]
Tested, it works!

**Comment by Wohlstand** [comment]
Also, @sezero, for a curious I checked out the code of MikMod, and the logic is same: `npt > 16`:

https://github.com/WohlSoft/AudioCodecs/blob/master/libmikmod/loaders/load_imf.c#L554
