### ISSUE TITLE
Extended Schism Tracker version information

### ISSUE THREAD

**Issue by sagamusix** [cmatsuoka/libxmp#154]
On 2020-10-28, the current Schism Tracker version format as found in IT and S3M headers will overflow. This was of course known beforehand so 0xFFF was declared to be a reserved value for any date starting from that day.

Since it's only one year until this format will overflow, I went ahead and prepared Schism Tracker for that day: If the version is 0xFFF, the *real* version is now stored in IT's reserved header field, or in the first two bytes of the unused 8 consecutive bytes in the S3M header. The data in these reserved fields follows the same as the value in `cwtv`, but without the tracker ID in the highest nibble (obviously), and 0x050 is not added to the value.

The attached files can be used to test the new version storage. They should decode as SchismTracker 2020-10-29.

[20201029.zip](https://github.com/schismtracker/schismtracker/files/3763851/20201029.zip)

**Comment by NoSuck** [comment]
Let me get this straight.  Schism burned through all 65,536 possible values of `cmwt` (perhaps by skipping over the vast majority of them in using a date-based version), so now it's going to break the IT spec and store version information in a non-standard location?

**Comment by sagamusix** [comment]
Nope.

1. First off, it's 4096 values (12 bits, the highest nibble is the tracker ID). Schism Tracker uses a date-based format system (days since 2009-09-31). It is true that this means there are a lot of versions but that doesn't matter.
2. Writing something to a "reserved" value that Impulse Tracker itself uses in an undocumented way (it counts the seconds you have been editing a file there - nobody was probably aware of that until I figured it out from reading the code) is not violating any specs.

**Comment by NoSuck** [comment]
How was this “of course not known beforehand”?

> Writing something to a "reserved" value... is not violating any specs.

I did not suggest that it was.  I also did not suggest to burn other trackers.  I am, however, confused as to what you would like libxmp to do about Schism having such a unique version situation.  Did you submit a PR?

Either way, thank you for the heads up.  Schism is an important tracker, and @cmatsuoka is generally accepting of fringe cases (as they are a big part of what libxmp is all about).

**Comment by sagamusix** [comment]
> How was this “of course not known beforehand”?

Sorry, freudian typo... It *was* known of course, and 0xFFF (the highest possible version value) was defined to be a reserved value.

>  I am, however, confused as to what you would like libxmp to do about Schism having such a unique version situation

libxmp's fingerprinting needs to be updated, that is what I was pointing out. It generally needs to be updated for *any* new tracker, no matter if it makes use of "non-standard" fields or not for storing its version information: while it's nice that IT has a field for indicating some version number, this field is not enough to be able to just identify any new tracker without adding special code to handle it - you need specific knowledge of each and every track in order to be able to identify them in a human-readable way.

>  Did you submit a PR?

Not yet, and I will only do so if I have too much time on my hands, which currently is sadly not the case.

**Comment by sagamusix** [comment]
(there is no rush to implement this btw, as it's still slightly more than a year until the new style of version storage is going to be seen in actual files apart from these test files - but it's always good to be prepared earlier than that.)

**Comment by AliceLR** [comment]
Working on this now. Turns out xmp refuses to load these files right now because they're smaller than the 256 byte check after depacking. Not a problem, but I thought that was funny.
