### ISSUE TITLE
memio wrongly uses errno and doesn't always set error

### ISSUE THREAD

**Issue by sezero** [cmatsuoka/libxmp#160]
Was initially reported at https://github.com/cmatsuoka/libxmp/issues/156

It should be made similar to dataio an using additional `int *err` param.
I can have a look at it if no one else does.

**Comment by sezero** [comment]
PING? Comments?

**Comment by sezero** [comment]
PING? Comments?

**Comment by sezero** [comment]
PING? Comments?

**Comment by AliceLR** [comment]
Just took a glance at this and it definitely looks wrong—IMO a cleaner solution might be to have memio.c store the error code in the MFILE struct instead of returning it through a param, but the param would be more consistent with dataio.c.

**Comment by sezero** [comment]
Will work on this as time permits, and send a patch (PR) here.

**Comment by sezero** [comment]
Please review and test this commit in 'memio-errno' branch:
https://github.com/cmatsuoka/libxmp/commit/7fca0237d96e45c91e85403993d0e10e62e4f907

With this, SONG6.PSM from #156 (where this issue was first noted) still plays for me.

**Comment by AliceLR** [comment]
I gave this a glance last night and it plays SONG6.PSM fine, but I couldn't reproduce any SONG6.PSM issues in master (possibly thanks to the mseek fix...). Since MASI uses an IFF wrapper it might not be the best format to stress test this with. I'll review the code changes (and try truncating some other files and comparing) soon...

**Comment by AliceLR** [comment]
From code inspection most of the patch looks good but I found two possible bugs:

[hio.c line 214](https://github.com/cmatsuoka/libxmp/commit/7fca0237d96e45c91e85403993d0e10e62e4f907#diff-39ef2e46e187094e070f174b6edaf8dcacb1fc0aade9daf711f8a3dca5c76ba4R213) has an accidental fall-through:
```C
	case HIO_HANDLE_TYPE_MEMORY:
		ret = mread32b(h->handle.mem, &err);
	default:
		return 0;
```

[mdataio.h line 29](https://github.com/cmatsuoka/libxmp/commit/7fca0237d96e45c91e85403993d0e10e62e4f907#diff-b325968a754179381e79d78fc29a4a60e2b9a2a926c42aa762dd241196309b98R29) sets err=EOF when the mgetc result is valid and sets err=0 when mgetc returns EOF:
```C
	int r = mgetc(m);
	if (err) {
	    *err = (r < 0) ? 0 : EOF;
	}
```

Also unrelatedly I think `make devcheck` broke in a couple of places... I'll look into that.

**Comment by sezero** [comment]
> [hio.c line 214](https://github.com/cmatsuoka/libxmp/commit/7fca0237d96e45c91e85403993d0e10e62e4f907#diff-39ef2e46e187094e070f174b6edaf8dcacb1fc0aade9daf711f8a3dca5c76ba4R213) has an accidental fall-through:

Fixed: https://github.com/cmatsuoka/libxmp/commit/5299db65ade21192c40faf0290d91430c6417f3f

> [mdataio.h line 29](https://github.com/cmatsuoka/libxmp/commit/7fca0237d96e45c91e85403993d0e10e62e4f907#diff-b325968a754179381e79d78fc29a4a60e2b9a2a926c42aa762dd241196309b98R29) sets err=EOF when the mgetc result is valid and sets err=0 when mgetc returns EOF:

https://github.com/cmatsuoka/libxmp/commit/93c9715dc571aad07e1f0f2823793b87ce725ab9

> Also unrelatedly I think `make devcheck` broke in a couple of places... I'll look into that.

Thanks.

**Comment by sezero** [comment]
> Also unrelatedly I think `make devcheck` broke in a couple of places... I'll look into that.

Test 12 has been failing since 0db60b18ad49884b at line 99:
https://github.com/cmatsuoka/libxmp/blob/master/test-dev/test_read_mem_hio.c#L98
That line tries to seek past end of file, and code before that seek commit
returned error, but it silently ignores it and seeks to end.

**Comment by sezero** [comment]
memio-errno branch rebased to master and the changesets squashed into a single commit
https://github.com/cmatsuoka/libxmp/commit/ad492e1ffa85f87ace4e269ae33846e9af68c4ce

**Comment by AliceLR** [comment]
This passes all of the tests in test-dev on my end (sorry for that detour and also for the followup patch...). I still want to try truncating some files to see if there's a difference before and after this patch, but it looks good to me.

**Comment by sezero** [comment]
I'll wait for your results.

**Comment by AliceLR** [comment]
Giving this a closer look I think I'm wrong and it's not possible to break the old implementation like that. It would keep attempting reads until it tries to read a larger value but it would still bounds check the memio reads. Regardless, I think this patch is correct.

**Comment by sezero** [comment]
OK then, merged the patch as https://github.com/cmatsuoka/libxmp/commit/e39c4a01a9fca4bf926111dda526975c978d9d5f

Closing this one. If issues arise, please open a new bug entry.
