### ISSUE TITLE
p61a.c: wrong memset?

### ISSUE THREAD

**Issue by softwarefailure** [cmatsuoka/libxmp#170]
While browsing `loaders/prowizard/p61a.c` I noticed this line at the beginning of `depack_p61a`:

    memset(isize, 0, 31 * 2);

`isize`, however, is declared as:

    int isize[31];

So `memset` doesn't clear the whole array with an integer size of 4 (which is the case on almost all compilers today). It looks like this line should be fixed like this:

    memset(isize, 0, 31 * sizeof(int));

Otherwise it looks like this line could access uninitialized memory:

    isize[i] = isize[0xffff - j];

**Comment by AliceLR** [comment]
There are a lot of memsets in the loaders dir (particularly the prowizard loaders) with fixed size lengths that should probably also be checked just in case. Looking at this now.

**Comment by sezero** [comment]
> There are a lot of memsets in the loaders dir (particularly the prowizard loaders) with fixed size lengths

Yes, and they can be confusing. Most of them (apart from a few partial memsets) should be
converted to use sizeof(array)

> that should probably also be checked just in case. Looking at this now.

Thanks

**Comment by AliceLR** [comment]
An impressive number of these had already been caught and fixed but I found some more that weren't:

In novotrade.c, though I don't think it uninitialized data can actually be read from this one:
```C
int pat_addr[128];
```
```C
memset(pat_addr, 0, 256);
```

pm10c.c, pm18a.c, pm20.c, pm40.c have these arrays that are never used but still not completely initialized, probably never caught for obvious reasons:
```C
short pptr[64][256];
```
```C
memset(pptr, 0, 64 << 8);
```

pp30.c (not sure at a glance if uninitialized data can be used here but it may be possible):
```C
short Tracks_PrePointers[512][64];
```
```C
memset(Tracks_PrePointers, 0, 512 * 64);
```

qc.c is fine in DOS and Windows where `long` is 4 bytes but this might be problematic on Linux:
```C
long iaddr[32];
long isize[32];
long paddr[128];
```
```
memset(iaddr, 0, 32 * 4);
memset(isize, 0, 32 * 4);
memset(paddr, 0, 128 * 4);
```

Same in tp2.c:
```C
long Track_Address[128][4];
```
```C
memset(Track_Address, 0, 128 * 4 * 4);
```

**Comment by sezero** [comment]
I started working on this two times and left it in boredom in both cases.
Thanks for doing this, impressive patience.

**Comment by AliceLR** [comment]
Patching it wasn't so bad since I had a list of affected files but self-reviewing it to be reasonably sure I didn't mess anything up was much worse. I am not surprised no one touched these before now.

**Comment by sezero** [comment]
The use of long type in there needs revising. See, e.g. pm20.c, and others.
But that's for another time.
