### ISSUE TITLE
test-dev issues.

### ISSUE THREAD

**Issue by AliceLR** [cmatsuoka/libxmp#181]
There were a couple of bugs preventing test-dev from building that I fixed and doing so revealed some broken tests. I would just fix them and submit a patch since they're mostly related to fixed bugs but I can no longer get `gen_module_data.py` to work.

Branch with the test-dev fixes (fnmatch.o → xfnmatch.o, plus moving some variables inside of the test scope to avoid redefinitions, plus slightly improved test failure output): https://github.com/cmatsuoka/libxmp/compare/master...AliceLR:fix-test-dev

Failed tests:
```
test 12: test_read_mem_hio: FAILED at test_read_mem_hio.c:99: hio_seek
test 76: test_loader_stm: FAILED at util.c:200: number of subinstruments
test 82: test_loader_far: FAILED at util.c:295: track data
```

Patches that likely caused these:
https://github.com/cmatsuoka/libxmp/pull/157
https://github.com/cmatsuoka/libxmp/pull/93
https://github.com/cmatsuoka/libxmp/pull/176

The .STM and .FAR tests should just be a matter of regenerating the module data hashes. The hio_seek fail might be resolved by the patch for #160 or that check might just need to be changed.

**Comment by AliceLR** [comment]
Actually, I'm not sure if I ever got `gen_module_data.py` to work. It's possible that back when I did that GDM test fix I just got util.c to dump the correct hash... :|

**Comment by sezero** [comment]
> test 12: test_read_mem_hio: FAILED at test_read_mem_hio.c:99: hio_seek

Test 12 has been failing since 0db60b18ad49884b at line 99:
https://github.com/cmatsuoka/libxmp/blob/master/test-dev/test_read_mem_hio.c#L98
That line tries to seek past end of file, and code before that seek commit
returned error, but now it silently ignores it and seeks to end.

**Comment by sezero** [comment]
>  The hio_seek fail might be resolved by the patch for #160 or that check might just need to be changed.

I think that check might need changing.

**Comment by sezero** [comment]
> > The hio_seek fail might be resolved by the patch for #160 or that check might just need to be changed.
> 
> I think that check might need changing.

Rationale: it is fseek / lseek behavior to not error upon seeking past end of file.
Run the following on a file named "0" which is 1 bytes long:
```
   int fd; FILE *f;

   fd=open("0",O_RDONLY);
   printf("lseek: %ld\n",lseek(fd,20,SEEK_CUR));
   close(fd);

   f = fopen("0","rb");
   fseek(f,20,SEEK_CUR);
   printf("ferror: %d\n",ferror(f));
   printf("feof: %d\n",feof(f));
   fclose(f);

$ ./a.out 
lseek: 20
ferror: 0
feof: 0
```

**Comment by AliceLR** [comment]
Thanks for looking into that, I thought that might be the case when I saw that but I wanted to be sure before changing it.

I added a C reimplementation of gen_module_data.py to that branch in commit 1169c114 so I should be able to fix the other two failed tests as well.

**Comment by sezero** [comment]
There are still 9 tests failing for me:
```
test 283: test_openmpt_xm_delay3: FAILED at compare_mixer_data.c:73: position mismatch
test 291: test_openmpt_xm_finevol_linkmem: FAILED at compare_mixer_data.c:73: position mismatch
test 293: test_openmpt_xm_key_off: FAILED at compare_mixer_data.c:73: position mismatch
test 295: test_openmpt_xm_keyoff_instr: FAILED at compare_mixer_data.c:73: position mismatch
test 299: test_openmpt_xm_noteoff2: FAILED at compare_mixer_data.c:73: position mismatch
test 319: test_openmpt_xm_tremolowaveforms: FAILED at compare_mixer_data.c:73: position mismatch
test 369: test_openmpt_it_samplenumberchange: FAILED at compare_mixer_data.c:73: position mismatch
test 372: test_openmpt_it_stoppedinstrswap: FAILED at compare_mixer_data.c:73: position mismatch
test 379: test_openmpt_it_wnoteoff: FAILED at compare_mixer_data.c:62: time mismatch
```
But they look irrelevant to any of the recent changes, I think.

**Comment by AliceLR** [comment]
I can't reproduce those failures. I rebuilt libxmp and test-dev with AddressSanitizer hoping it would find something in those tests but instead it found several other tests with issues (using screenshots here instead of text to preserve the highlighting):

![image](https://user-images.githubusercontent.com/1750531/97790063-321b8300-1b8b-11eb-96e6-3c24517fd020.png)
![image](https://user-images.githubusercontent.com/1750531/97790080-4fe8e800-1b8b-11eb-9d96-2c2506a55421.png)
![image](https://user-images.githubusercontent.com/1750531/97790098-62632180-1b8b-11eb-8656-8f2943f739c2.png)
![image](https://user-images.githubusercontent.com/1750531/97790112-727b0100-1b8b-11eb-8a44-e2c9e975c209.png)

**Comment by AliceLR** [comment]
Looks like those are my fault, the MDL loader provides strings shorter than 4 bytes there... :/

**Comment by sezero** [comment]
> I can't reproduce those failures.

I'm on a 32 bit (i686) host, will switch to a 64 bit one to test again, see if they still fail.

**Comment by AliceLR** [comment]
Ok. I will test with my Core Duo iMac's Snow Leopard and Linux Mint installations (when it stops updating packages anyway...) and with my 32-bit PowerPC VM and return with anything interesting I find.

**Comment by sezero** [comment]
On an x86_64 linux (my old Fedora 27 setup), no devcheck failures. Huh.. Will try investigating as time permits.

**Comment by AliceLR** [comment]
I reproduced those failures on my iMac:
```
test 283: test_openmpt_xm_delay3: at compare_mixer_data.c:73: position mismatch: **fail**
test 291: test_openmpt_xm_finevol_linkmem: at compare_mixer_data.c:73: position mismatch: **fail**
test 293: test_openmpt_xm_key_off: at compare_mixer_data.c:73: position mismatch: **fail**
test 295: test_openmpt_xm_keyoff_instr: at compare_mixer_data.c:73: position mismatch: **fail**
test 299: test_openmpt_xm_noteoff2: at compare_mixer_data.c:73: position mismatch: **fail**
test 319: test_openmpt_xm_tremolowaveforms: at compare_mixer_data.c:73: position mismatch: **fail**
test 369: test_openmpt_it_samplenumberchange: at compare_mixer_data.c:73: position mismatch: **fail**
test 372: test_openmpt_it_stoppedinstrswap: at compare_mixer_data.c:73: position mismatch: **fail**
test 379: test_openmpt_it_wnoteoff: at compare_mixer_data.c:62: time mismatch: **fail**
```
PPC VM still pending because it's compiling these tests at about a rate of 1 test per second.

**Comment by sezero** [comment]
OK, reopening this one until we figure it out.

**Comment by AliceLR** [comment]
As far as I can tell the MDL test is failing because it does not convert the 16-bit samples loaded from the MDL to little endian. This patch fixes it and should prevent it from being an issue with other tests in the future (going to hold off on the PR until we've figured out all of these and this has been tested some more...):

```diff
diff --git a/test-dev/util.c b/test-dev/util.c
index bbe2447f..2ceea0b4 100644
--- a/test-dev/util.c
+++ b/test-dev/util.c
@@ -302,8 +302,13 @@ int compare_module(struct xmp_module *mod, FILE *f)
 		MD5_CTX ctx;
 		int len = xxs->len;
 
-		if (xxs->flg & XMP_SAMPLE_16BIT)
+		if (xxs->flg & XMP_SAMPLE_16BIT) {
 			len *= 2;
+			/* Normalize data to little endian for the hash. */
+			if (is_big_endian()) {
+				convert_endian(xxs->data, xxs->len);
+			}
+		}
 
 		read_line(line, 1024, f);
 		x = strtoul(line, &s, 0);
@@ -482,8 +487,13 @@ void dump_module(struct xmp_module *mod, FILE *f)
 		MD5_CTX ctx;
 		int len = xxs->len;
 
-		if (xxs->flg & XMP_SAMPLE_16BIT)
+		if (xxs->flg & XMP_SAMPLE_16BIT) {
 			len *= 2;
+			/* Normalize data to little endian for the hash. */
+			if (is_big_endian()) {
+				convert_endian(xxs->data, xxs->len);
+			}
+		}
 
 		fprintf(f, "%u %u %u %u",
 			xxs->len, /* sample length */
```

**Comment by sezero** [comment]
About the vorbis depack failure on PPC:  Maybe it's something to do with endianism.
I looked at vorbis.c, there is STB_VORBIS_BIG_ENDIAN macro, but it does nothing.
Around line 4959 where the STB_VORBIS_NO_FAST_SCALED_FLOAT ifdef block is,
check_endianness() is always defined as an empty macro.

**Comment by AliceLR** [comment]
It looks like the upstream stb_vorbis has the same problem. https://github.com/nothings/stb/blob/master/stb_vorbis.c

**Comment by sezero** [comment]
Does the following help with vorbis on ppc?
```
diff --git a/src/depackers/oxm.c b/src/depackers/oxm.c
index 8fa1364..66ebe5f 100644
--- a/src/depackers/oxm.c
+++ b/src/depackers/oxm.c
@@ -296,6 +296,17 @@ static int decrunch_oxm(FILE *f, FILE *fo)
                                if (pcm[j] == NULL) {
                                        return -1;
                                }
+#ifdef WORDS_BIGENDIAN
+                               if (res == 16) {
+                               /* convert host-endian to little-endian */
+                                       int16 *p = (int16 *) pcm[j]; int k;
+                                       newlen /= 2;
+                                       for (k = 0; k < newlen; ++k, ++p) {
+                                               *p = (*p & 0xFF) << 8) |
+                                                   ((*p >> 8) & 0xFF);
+                                       }
+                               }
+#endif
                        }
                }
 
```

**Comment by AliceLR** [comment]
That does not fix the test failure. It fails the first comparison (expects -769, result is -4). I think this is also the same result I got when I added a check to flip the sample bytes to the test itself.

For reference, the failure without any changes aside from adding a debug line is:
| sample | expected | actual |
|-|-|-|
| 0 | -769 | -769 |
| 1 | -1537 | -1282 |

**Comment by AliceLR** [comment]
Something interesting about all of the fields that get flagged in those tests that fail on 32-bit machines: they're all derived from doubles. `xmp_frame_info::time` comes from the `player_data::current_time` field and `xmp_channel_info::position` comes from `channel_data::info_position`, which gets initialized off of the return value from `libxmp_virt_getvoicepos`. I added a debug line to check those values and sure enough, they were all off by one!

Updated patch:
```diff
diff --git a/test-dev/compare_mixer_data.c b/test-dev/compare_mixer_data.c
index f59fbde3..89eb083d 100644
--- a/test-dev/compare_mixer_data.c
+++ b/test-dev/compare_mixer_data.c
@@ -59,7 +59,8 @@ static void _compare_mixer_data(char *mod, char *data, int loops, int ignore_rv)
 				&time, &row, &frame, &chan, &period,
 				&note, &ins, &vol, &pan, &pos0, &cutoff);
 
-			fail_unless(fi.time    == time,   "time mismatch");
+			/* Allow some error in values derived from floating point math. */
+			fail_unless(abs(fi.time - time) <= 1, "time mismatch");
 			fail_unless(fi.row     == row,    "row mismatch");
 			fail_unless(fi.frame   == frame,  "frame mismatch");
 			fail_unless(i          == chan,   "channel mismatch");
@@ -70,7 +71,7 @@ static void _compare_mixer_data(char *mod, char *data, int loops, int ignore_rv)
 				fail_unless(vi->vol == vol, "volume mismatch");
 				fail_unless(vi->pan == pan, "pan mismatch");
 			}
-			fail_unless(vi->pos0   == pos0,   "position mismatch");
+			fail_unless(abs(vi->pos0 - pos0) <= 1, "position mismatch");
 			if (num >= 11) {
 				fail_unless(vi->filter.cutoff == cutoff,
 							  "cutoff mismatch");
diff --git a/test-dev/util.c b/test-dev/util.c
index bbe2447f..2ceea0b4 100644
--- a/test-dev/util.c
+++ b/test-dev/util.c
@@ -302,8 +302,13 @@ int compare_module(struct xmp_module *mod, FILE *f)
 		MD5_CTX ctx;
 		int len = xxs->len;
 
-		if (xxs->flg & XMP_SAMPLE_16BIT)
+		if (xxs->flg & XMP_SAMPLE_16BIT) {
 			len *= 2;
+			/* Normalize data to little endian for the hash. */
+			if (is_big_endian()) {
+				convert_endian(xxs->data, xxs->len);
+			}
+		}
 
 		read_line(line, 1024, f);
 		x = strtoul(line, &s, 0);
@@ -482,8 +487,13 @@ void dump_module(struct xmp_module *mod, FILE *f)
 		MD5_CTX ctx;
 		int len = xxs->len;
 
-		if (xxs->flg & XMP_SAMPLE_16BIT)
+		if (xxs->flg & XMP_SAMPLE_16BIT) {
 			len *= 2;
+			/* Normalize data to little endian for the hash. */
+			if (is_big_endian()) {
+				convert_endian(xxs->data, xxs->len);
+			}
+		}
 
 		fprintf(f, "%u %u %u %u",
 			xxs->len, /* sample length */
```

**Comment by sezero** [comment]
Huh. Building with -msse2 -mfpmath=sse, got no failures, so you seem to be right: x87 issues.

**Comment by sezero** [comment]
> That does not fix the test failure. [...]

I think it's because beep.raw is written as little-endian but is read on big-endian.
Can you try once more with the following patch on top of my previous oxm.c patch:
```
diff --git a/test-dev/test_depack_vorbis.c b/test-dev/test_depack_vorbis.c
index e8dbdd3..9d36027 100644
--- a/test-dev/test_depack_vorbis.c
+++ b/test-dev/test_depack_vorbis.c
@@ -29,6 +29,9 @@ TEST(test_depack_vorbis)
        fclose(f);
 
        pcm16 = (int16 *)info.mod->xxs[0].data;
+       if (is_big_endian()) { /* convert little-endian to host-endian */
+               convert_endian((unsigned char *)buf, st.st_size / 2);
+       }
 
        for (i = 0; i < (9376 / 2); i++) {
                if (pcm16[i] != buf[i])
```

**Comment by sezero** [comment]
> > That does not fix the test failure. [...]
> 
> I think it's because beep.raw is written as little-endian but is read on big-endian.
> Can you try once more with the following patch on top of my previous oxm.c patch:

Tried on my mac under Rosetta, the vorbis test did not fail.  If you confirm, I will
push the patch.

**Comment by AliceLR** [comment]
I can confirm that with both patches it works in my VM too (I'm glad that was the only other thing that needed to be fixed...).

**Comment by sezero** [comment]
Shall I push your patch from above?

About the second part of your patch (endian): Is MDL (the only failure on ppc)
the only format tested with 16 bit samples?

**Comment by sezero** [comment]
Pushed my oxm.c and test_depack_vorbis.c endian patches.

> Shall I push your patch from above?

Went ahead and push the first part of your patch to compare_mixer_data.c

> About the second part of your patch (endian): Is MDL (the only failure on ppc)
> the only format tested with 16 bit samples?

Waiting this one for your response.

**Comment by AliceLR** [comment]
It isn't necessarily the only format being tested with 16-bit samples but it was the only one using `compare_module`. I added a debug line to confirm this. I think it's reasonable to assume that future tests may be added containing 16-bit samples that need `compare_module` though.

**Comment by sezero** [comment]
OK, applied that part too.

Closing this one.
