### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by AntonZab** [cmatsuoka/libxmp#19]
Hello. I want to ask you. So I downloaded your source libxmp. But I do not know how to compile them. I Download software NetBeans. Downloaded MinGW. But this program does not understand files Makefile.in and Makefile.am. She needs a ready Makefile. Tell me how to work with these files. What program and how to compile them. I should Win7 and WinXP 32bit. Linux and other systems are not installed. Thanks in advance

**Comment by cmatsuoka** [comment]
Hi,

Using MinGW, running './configure' should create Makefile from Makefile.in.
Using Visual C++, 'nmake -f Makefile.vc' should build the DLL.

**Comment by AntonZab** [comment]
Thanks
