### ISSUE TITLE
c++ compatibility

### ISSUE THREAD

**Issue by sezero** [cmatsuoka/libxmp#191]
```
$ cat 0.cc
#include "xmp.h"
struct xmp_subinstrument si;
struct xmp_channel_info ci;

$ g++ -Wall -W -Wextra -c 0.cc
0.cc:2: error: aggregate ‘xmp_subinstrument si’ has incomplete type and cannot be defined
0.cc:3: error: aggregate ‘xmp_channel_info ci’ has incomplete type and cannot be defined
```

Should users be able to use those structures? If yes,
they should be moved out of struct xmp_instrument and
struct xmp_frame_info.

**Comment by AliceLR** [comment]
The example works when I change it to:
```C++
#include "xmp.h"
xmp_instrument::xmp_subinstrument si;
xmp_frame_info::xmp_channel_info ci;
```

If I was writing C++ code referencing those types I wouldn't mind writing them like that but since moving them out could improve C/C++ interoperability it may be a good idea to do that anyway.
