### ISSUE TITLE
PP30 packed MODs

### ISSUE THREAD

**Issue by AntonZab** [cmatsuoka/libxmp#20]
Hi. In the source code libxmp have a folder Prowizard. There is a list of formats. For example: pp21 pp30. I pp21 plays perfectly. But pp30 just do not recognize. Why so? Are all supported formats with folders Prowizard?

**Comment by cmatsuoka** [comment]
Hi,

PP30 was never compiled because I don't have any files to test the format.
If you have some, could you send me for tests?

**Comment by AntonZab** [comment]
I have one file. The rest as found. Tell me how do I send you. does not work

**Comment by AntonZab** [comment]
I found another 3.

**Comment by AntonZab** [comment]
http://www.exotica.org.uk/wiki/Jimmy's_Fantastic_Journey

**Comment by AntonZab** [comment]
So. What about pp30?

**Comment by cmatsuoka** [comment]
Done. Will be available in the next release.

**Comment by AntonZab** [comment]
And what about these formats?

Promizer Packer 0.1
Promizer Packer 2.0
Promizer Packer 4.0
ProPacker 1.0
ProPacker 3.0
Pro-Wizard 1.c
TrackerPacker 1.c
TrackerPacker 2.c

Theirs codes as there is in the folder Prowizard
