### ISSUE TITLE
Other Formats in prowizard

### ISSUE THREAD

**Issue by AntonZab** [cmatsuoka/libxmp#21]

**Comment by AntonZab** [comment]
Hi. what about these formats?

Promizer Packer 0.1
Promizer Packer 2.0
Promizer Packer 4.0
ProPacker 1.0
TrackerPacker 1.c
TrackerPacker 2.c

Theirs codes as there is in the folder Prowizard.
If you need samples, I'll give them to you.

Promizer Packer 0.1
http://bzrplayer.blazer.nu/getSample.php?id=352

Promizer Packer 2.0
http://bzrplayer.blazer.nu/getSample.php?id=354

Promizer Packer 4.0
http://bzrplayer.blazer.nu/getSample.php?id=362

ProPacker 1.0
http://bzrplayer.blazer.nu/getSample.php?id=355

TrackerPacker 1.c
has not yet found

TrackerPacker 2.c
http://bzrplayer.blazer.nu/getSample.php?id=86

**Comment by cmatsuoka** [comment]
Thanks. I'll check these and add in the next development cycle.

**Comment by AsleAMP** [comment]
Well, I sent many examples to the BZR guy quite some time ago. Got a TP1 handy if needed (from Paeckchen 45 packmenu by Mexx)
