### ISSUE TITLE
Latest GitHub xmp/libxmp cannot play sll7.mod from modarchive (ModPlug players play it fine)

### ISSUE THREAD

**Issue by shlomif** [cmatsuoka/libxmp#28]
Hi!

Thanks for libxmp and XMP.

sll7.mod from http://modarchive.org/index.php?request=view_by_moduleid&query=57470 (also available here - http://www.shlomifish.org/Files/files/music/mp3-ogg/sll7.mod ) cannot be played using the GitHub master HEAD libxmp+xmp combo, while playing it with VLC and mplayer which both use libModPlug works fine:

```text
shlomif@telaviv1:~$ LD_LIBRARY_PATH=$HOME/apps/libxmp/lib /home/shlomif/apps/libxmp/bin/xmp ./sll7.mod 
Extended Module Player 4.0.10
Copyright (C) 1996-2014 Claudio Matsuoka and Hipolito Carraro Jr
Using PulseAudio sound output
Mixer set to 44100 Hz, 16bit, cubic spline interpolated stereo
Press 'h' for help

Loading ./sll7.mod (1 of 1)
/home/shlomif/apps/libxmp/bin/xmp: ./sll7.mod: Unrecognized file format
shlomif@telaviv1:~$ 

```

Please look into correcting it.

**Comment by cmatsuoka** [comment]
This is an interesting one. The original rip cut the file after the last
sample actually used, making the file too short for the list of samples (so
it's not recognized as a Soundtracker module). We can change the test to
check the minimum file size without unused samples at the end. If we try to
actually load the module, the last sample won't load correctly. At this
point we can: 1) be permissive and allow loading potentially corrupt files;
2) refuse to load them (and ssl7.mod won't load); or 3) mix the two
approaches making used samples mandatory and unused samples optional. We'll
implement this mixed approach in the Soundtracker loader, hoping that we
won't have similar problems in other formats.

**Comment by shlomif** [comment]
Thanks,  @cmatsuoka ! 

BTW, I recently ran into a file of the format AHX - https://en.wikipedia.org/wiki/Module_file#Popular_formats - on modarchive.org and xmp was unable to play it:

http://modarchive.org/index.php?request=view_by_moduleid&query=163514

Any chance of libxmp/XMP supporting this format?

Regards,

-- @shlomif

**Comment by mldoering** [comment]
Hej Claudio, hej shlomif,

concerning the sll7tracker mod - I think a bad rip. AMP has two versions of the file that should work, a soundtracker with 15 instr. and a noisetracker mod:
http://amp.dascene.net/detail.php?detail=modules&view=6784

THX/AHX uses synth instruments and filters, not sure if it's in xmp's scope. There's hivelytracker https://github.com/pete-gordon/hivelytracker

**Comment by cmatsuoka** [comment]
Since sll7 is working, I'll close this issue. The corrupt file is most certainly a bad rip. We're currently handling it (but we may refuse corrupt files in the future if the hack that allows this file to be loaded causes problems with other modules).

We'll focus in improving existing formats (especially the main four formats, MOD, XM, S3M and IT) instead of adding support to new formats. AHX support could happen in the future (I have the format description in the repository) but it won't be at high priority anytime soon.

**Comment by shlomif** [comment]
Thanks!
