### ISSUE TITLE
libxmp 4.1+ cuts off Fasttracker 2 module name

### ISSUE THREAD

**Issue by mistydemeo** [cmatsuoka/libxmp#3]
The module name for a specific Fasttracker 2 song, Zoo Connections by Drax, is cut off when using libxmp 4.1 and newer. For example, the xmp output:

4.0.4:
> Module name  : ZOO-CONNEXIONS: DRAX

4.1.5:
> Module name  : ZOO-CONNEXIONS: DRA

I've tested with both xmp and pyxmp, so it does look like a libxmp bug rather than an xmp bug.

The module can be downloaded from Modland: http://files.exotica.org.uk/modland/?file=pub/modules/Fasttracker%202/Drax/zoo-connections%21.xm

**Comment by cmatsuoka** [comment]
Fixed (presumably) in 4.2.0, but issue was left open. Closing it now.
