### ISSUE TITLE
Problems detected by ASan/MSan

### ISSUE THREAD

**Issue by neuschaefer** [cmatsuoka/libxmp#31]
I've done a small bit of debugging on the test case failures:

- `test_sample_load_endian` fails because load_sample will load 20 bytes starting from `conv_r0`. Setting `xxs.len = 5` seems to fix it.
- `test_depack_vorbis_8bit` works if I change the loop to `for (i = 0; i < 496; i++)`, otherwise ASan complains that we're reading out of bounds of a 500-byte allocation.
- `test_loader_m15_short_rip` fails under both ASan and MSan. It probably fails under ASan because ASan initializes nominally uninitialized memory with 0xbe bytes. Debugging uninitialized memory warnings MSan is a little harder with than the errors reported by ASan, because the control flow has to depend on an uninitialized value for it to be detected; copying it somewhere isn't enough and `printf`ing it doesn't trigger MSan either.
- `test_api_smix_play_sample` fails because `mod` in `read_event_smix` points into unallocated heap memory.

I've also used [afl-fuzz] on libxmp, and it found a bunch of issues triggered by malformed input files. Many of them are out-of-bounds reads, but some are more serious, as they corrupt data on the heap or stack.

[afl-fuzz]: http://lcamtuf.coredump.cx/afl/

**Comment by cmatsuoka** [comment]
The sanitizer is a very interesting tool, thanks for adding it to the integration. I'm fixing the problems and hopefully we'll have a clean build soon. Could you send me the fuzzed files that cause problems so I can add the appropriate sanity checks?

**Comment by neuschaefer** [comment]
Yes, I'll send you an e-mail.
