### ISSUE TITLE
Incorrect Stereo Separation of IT Files

### ISSUE THREAD

**Issue by NoSuck** [cmatsuoka/libxmp#35]
The following images show captured playback of the same IT file posted to issue #34.  Channel 1 pans 100% left (0), and channel 2 pans 200% right (64).  Libxmp's output does not completely pan the channels.

![libxmp](https://nosuckdotorg.files.wordpress.com/2015/07/note-off-fadeout-256-screen-libxmp.png)
Libxmp

![Impulse Tracker](https://nosuckdotorg.files.wordpress.com/2015/07/note-off-fadeout-256-screen-impulse-tracker.png)
Impulse Tracker

**Comment by cmatsuoka** [comment]
To set stereo mix to 100%, set XMP_PLAYER_MIX to 100 using xmp_player_set(). This is the called in the command-line player using the -P parameter. The default is set to 70% to sound less harsh in headphones.

Using -P100 and the fix in 3ef27130d211f7ec1bd388cea3faaa34328f2983 the result should be:

![image](https://cloud.githubusercontent.com/assets/317355/9026236/65b2c81a-38fe-11e5-9f7e-12b5528caeae.png)

**Comment by sagamusix** [comment]
As NoSuck says, libxmp's behaviour is simply inappropriate for IT files. We all are of course aware of the horrible panning of Amiga MODs, but in general this is not an issue with more modern formats, and many IT files especially with stereo samples will suffer from the defaults here. Maybe the current default should really only be applied to Amiga formats, and maybe some early DOS formats that do not allow custom panning.

**Comment by cmatsuoka** [comment]
I'm changing the library default to 100% in version 4.4 (it was 70% in 4.3 and earlier). There's another setting for the default left/right pan used by default in old formats, so that should suffice to take care of mods with headphones.

**Comment by sagamusix** [comment]
Thanks. :)

**Comment by cmatsuoka** [comment]
There's a lot of old (and I mean 1996-old) ideas in the library underlyings. Some of them looked good at the time but they just don't cut it anymore (others looked bad at the time and would be "fixed later", hah). I really should refactor the entire thing based on current knowledge of format quirks and throw away the old cruft, but, ah, the laziness. There's also some rounding errors being spotted thanks to a no-floating-point policy that made sense in the 90s, but we're already working on these.
