### ISSUE TITLE
IT Gxx and Lxx Effects Do Not Reference Previous Values (As G00 and L00)

### ISSUE THREAD

**Issue by NoSuck** [cmatsuoka/libxmp#38]
Libxmp gets better every time I use it.  Thank you.

I have returned with two more IT test files, this time concerning the Gxx (portamento to note) and Lxx (G00 + Dxx, portamento continue + volume slide) effects.  The test module features a chromatic scale running up two channels, one with explicit notes and one with G00/L00 effects that continue a G08 contained in a previous row.  As can be heard, libxmp fails to use previous values of Gxx for both G00 and L00.  This seems to occur when the initial G08 does not coincide with a note.  The volume slide portion of L00 seems to work fine regardless.

I have uploaded with the test modules output capture both for Impulse Tracker and libxmp:

https://www.dropbox.com/sh/vhs0u7lmh0wmjwh/AABOXrirOTsG0LrJL8Hj5LeIa?dl=0

**Comment by cmatsuoka** [comment]
Good catch! The effect memory was being set after checking for a valid note. Fixed in commit b66b3af.
