### ISSUE TITLE
SC68 support

### ISSUE THREAD

**Issue by filevans** [cmatsuoka/libxmp#42]
Hello there
Please could you add SC68 / sndh support. And SID toó if possible. 
Thank you for listening

**Comment by cmatsuoka** [comment]
Adding support to these in the current library is hard and fixing replay of the "big four" module formats (MOD, S3M, XM, IT) is currently at a higher priority. The library requires modules organized in a tracker-like internal structure.

**Comment by filevans** [comment]
well thanks for your fast reply anyway

**Comment by cmatsuoka** [comment]
SID and SC68 will be better handled by specialized libraries in these formats. A player front-end should use different libraries to play the formats it needs.
