### ISSUE TITLE
xmp on OS X 10.11 El Capitan: deprecated Carbon Component Manager warning

### ISSUE THREAD

**Issue by dspreadbury** [cmatsuoka/libxmp#43]
I don't know if this is significant, but when I run xmp on my Mac running OS X 10.11 El Capitan, I see the following warning logged out to the Terminal before the module starts playing:

> 2015-10-07 15:45:21.014 xmp[69075:3855547] 15:45:21.013 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

I absolutely love xmp and am so grateful to you for working on it. Apologies if this issue is already known about. (I'm running xmp 4.0.6 and have been meaning to update to 4.1.0, so apologies also if this has been taken care of already.)

**Comment by cmatsuoka** [comment]
I finally updated my Mac to El Capitan (I had to keep it with Yosemite until the end of another project), and I didn't see any problems running xmp 4.0.10, so it seems that this problem is already fixed. If you still see the warning in a recent player version, please reopen!
