### ISSUE TITLE
Craches when playing some j2b

### ISSUE THREAD

**Issue by AntonZab** [cmatsuoka/libxmp#44]
Player Craches when playing some j2b (Galaxy Sound System). Work fine - castle.j2b

https://drive.google.com/file/d/0B0oEDro3cJx-blNIamRyLXRqb2c/view?usp=sharing

**Comment by cmatsuoka** [comment]
Acknowledged. A few J2B modules are not recognized as such. Fixing...

Loading Boss1.j2b (4 of 23)
xmp: Boss1.j2b: Error loading module

Loading Boss2.j2b (5 of 23)
xmp: Boss2.j2b: Error loading module

Loading Carrotus.j2b (6 of 23)
xmp: Carrotus.j2b: Error loading module

**Comment by cmatsuoka** [comment]
Very interesting! Your set of J2B modules are Galaxy 4 instead of the Galaxy 5 modules I have here (but Galaxy 5 modules are not loading correctly as well, so fixing both loaders now).

**Comment by cmatsuoka** [comment]
Fixed.

Loading Boss1.j2b (4 of 23)
Module name  : Jazz Boss Tune 2
Module type  : Galaxy Music System 4.0
Module length: 10 patterns
Patterns     : 8
Instruments  : 16
Samples      : 12
Channels     : 11 [ 8 8 8 8 8 8 8 8 8 8 8 ]
Duration     : 1min12s
Speed[06] BPM[85] Pos[09/09] Pat[04/07] Row[3F/3F] Chn[0A/0A]      0:01:12.0

Loading Boss2.j2b (5 of 23)
Module name  : Jazz Boss tune 1
Module type  : Galaxy Music System 4.0
Module length: 16 patterns
Patterns     : 21
Instruments  : 22
Samples      : 12
Channels     : 13 [ 8 8 8 8 8 8 8 8 8 8 8 8 8 ]
Duration     : 0min54s
Speed[03] BPM[6A] Pos[0F/0F] Pat[14/14] Row[2F/3F] Chn[0A/0A]      0:00:54.1

Loading Carrotus.j2b (6 of 23)
Module name  : Carrotus
Module type  : Galaxy Music System 4.0
Module length: 23 patterns
Patterns     : 32
Instruments  : 28
Samples      : 28
Channels     : 12 [ 8 8 8 8 8 8 8 8 8 8 8 8 ]
Duration     : 1min19s
Speed[03] BPM[85] Pos[16/16] Pat[1A/1F] Row[3F/3F] Chn[0C/0C]      0:01:19.0
