### ISSUE TITLE
Incorrect playback of an AMF file

### ISSUE THREAD

**Issue by speachy** [cmatsuoka/libxmp#50]
I'm not quite sure how to describe this in the correct technical terms, but it sounds as if specific notes are not properly held/sustained long enough (or the sample isn't being looped properly..)

The problem is audible less than 10 seconds into the file, at position 01/2E (pattern 15/23).
Both mikmod and and modplug123 play this particular file properly.

I'm using git head for both libxmp and xmp-cli as of this writing.
 
[crusader-space.zip](https://github.com/cmatsuoka/libxmp/files/139353/crusader-space.zip)

**Comment by mldoering** [comment]
Am Sat, 20 Feb 2016 13:36:42 -0800
schrieb Solomon Peachy <notifications@github.com>:

> I'm not quite sure how to describe this in the correct technical
> terms, but it sounds as if specific notes are not properly
> held/sustained long enough (or the sample isn't being looped
> properly..)
> 
> The problem is audible less than 10 seconds into the file, at
> position 01/2E (pattern 15/23). Both mikmod and and modplug123 play
> this particular file properly.
> 
> I'm using git head for both libxmp and xmp-cli as of this writing.
>  
> [crusader-space.zip](https://github.com/cmatsuoka/libxmp/files/139353/crusader-space.zip)


Hej Claudio,
Hi Solomon,

I tracked down the music as plain fasttracker to rule out a converter
bug and ran Sylvain Chipeaux' modinfo for you over the file and
attached the result.

Don't know if it helps you spotting the bug.

http://amp.dascene.net/downmod.php?index=88632

Michael/mld/Doering

generated by ModInfo v2.32 (Linux) - 2006 (c) Sylvain "Asle" Chipaux (asle@free.fr)
----
TITLE : 
FORMAT : Fastracker v1/v2 (8CHN)

WHOLE SAMPLE SIZE ..... : 251000
HEADER SIZE (HEAD+PAT). : 74812
FILE SIZE ............. : 325812
CALCULATED SIZE ....... : 325812


NBR  - NAME                     SIZE VOL FINE LSTART LSIZE   (Nbr times used)
[ 1] - "crusader" - misc12     33464  64   0      0      2         (60)
[ 2] -                          4036  64   3      0      2         (116)
[ 3] - composed by:             2464  64   3      0      2         (259)
[ 4] - basehead of              2308  64   3      0      2         (84)
[ 5] - straylight productions  34016  64   0  28000   4000         (10)
[ 6] -                         19000  64   0     62  18938         (3)
[ 7] - this song was made      10728  64   0     62  10666         (7)
[ 8] - exclusively for origin   8660  40   0   5820   2840         (42)
[ 9] -                          4292  64   0   1348   2944         (45)
[10] - copyright c and circle   2406  64   0      0      2         (295)
[11] - 1996 by basehead            0  64   0      0      2         (0)
[12] -                          5552  64   0      0      2         (807)
[13] -                          4688  34   0      0      2         (216)
[14] -                         11526  64   0      0      2         (308)
[15] -                         27326  64   0      0      2         (58)
[16] -                          4560  64   0      0      2         (363)
[17] -                          4000  44   0      0      2         (194)
[18] -                         26420  64   0      0      2         (18)
[19] -                         19552  64   0      0      2         (42)
[20] -                         21702  32   0  13698   8000         (22)
[21] -                             0  64   0      0      2         (0)
[22] -                             0  64   0      0      2         (0)
[23] -                          4300  60   0      0      2         (497)
[24] -                             0  64   0      0      2         (0)
[25] -                             0  64   0      0      2         (0)
[26] -                             0  64   0      0      2         (0)
[27] -                             0  64   0      0      2         (0)
[28] -                             0  64   0      0      2         (0)
[29] -                             0  64   0      0      2         (0)
[30] -                             0  64   0      0      2         (0)
[31] -                             0  64   0      0      2         (0)


SIZE OF THE PATTERN LIST : 47
"NOISETRACKER BYTE" : 127
PATTERN LIST :
20, 19, 21, 22, 23, 24, 25, 26, 26, 27, 
27, 28, 28, 30, 29, 30, 29, 31, 34,  0, 
 1,  2,  3,  4,  5,  6,  7,  8,  8, 28, 
28, 24, 25, 26, 27, 28, 28,  9, 10, 11, 
12, 30, 29, 31, 34,  0, 35, 

NUMBER OF PATTERNS STORED : 36

there is/are 8 unused pattern(s) :
-> 13, 14, 15, 16, 17, 18, 32, 33, 


PROTRACKER EFFECTS USED :
Arpeggio        [0] :    0   |  Set filter          [E0] :    0
Slide up        [1] :    0   |  Fine Slide up       [E1] :    0
Slide down      [2] :    0   |  Fine Slide down     [E2] :    0
Tone portamento [3] :    0   |  Set glissendo       [E3] :    0
Vibrato         [4] :    0   |  Set vibrato         [E4] :    0
3+A             [5] :    0   |  Set finetune        [E5] :    0
4+A             [6] :    0   |  Set loop            [E6] :    0
Tremolo         [7] :    0   |  Set tremolo         [E7] :    0
                [8] :    0   |                      [E8] :    0
Sample offset   [9] :    0   |  Rettriger           [E9] :    0
Volume slide    [A] :    0   |  Fine vol slide up   [EA] :    0
Position jump   [B] :    1   |  Fine vol slide down [EB] :    0
Set volume      [C] : 5643   |  Note cut            [EC] :    0
Pattern break   [D] :    1   |  Note delay          [ED] :    0
Set speed       [F] :    0   |  Pattern delay       [EE] :    0
Set BPM         [F] :    0   |  Invert loop         [EF] :    0


NOTES USED IN PATTERNS :
no note : 14986
C-3 :    2   | C-4 :    6   | C-5 :    6
C#3 :   52   | C#4 :  222   | C#5 :  102
D-3 :   17   | D-4 :    3   | D-5 :   23
D#3 :    0   | D#4 :   86   | D#5 :   44
E-3 :   37   | E-4 :  254   | E-5 : 1455
F-3 :    9   | F-4 :    1   | F-5 :    6
F#3 :   69   | F#4 :  285   | F#5 :  204
G-3 :    0   | G-4 :    0   | G-5 :   18
G#3 :  179   | G#4 :  194   | G#5 :   23
A-3 :   10   | A-4 :    7   | A-5 :    0
A#3 :    0   | A#4 :    6   | A#5 :    3
B-3 :   71   | B-4 :   32   | B-5 :   20
unknown not empty notes : 0

**Comment by cmatsuoka** [comment]
Hi Solomon and Michael,

I compared the output of the first three patterns of the song (up to approx 20s) between space.amf and the 8CHN module (which xmp thinks it's a Scream Tracker 3 8CHN instead of a Fast Tracker 8CHN), and they sound very similar to me. Comparing the outputs, they're indeed the same, so it's not a conversion problem or AMF loader error.

![image](https://cloud.githubusercontent.com/assets/317355/13205504/59cc2d56-d8c8-11e5-9cf6-6d030ec62be5.png)

The output in Scream Tracker 3 sounded very similar too (except for reversed L/R channels in DOSBox), so perhaps I'm not being able to pinpoint the error there. Could you try to identify the channel or instrument where the problem happens?

**Comment by speachy** [comment]
Just to be clear, I'm referencing the "original" AMF file extracted directly from the game (ie what I uploaded)

A self-contained example of the problem is Pattern 19, Channel 3, rows 0-15.  When it plays a note with instrument 8, the instrument (a bell of sorts) is supposed to sustain/loop until the it plays the next note at row 16, which should then be sustained until the next note is played at row 32.

When played with xmp, the bell cuts out prematurely; the instrument is not looping properly.  (I can recreate this effect by opening the file up in OpenMPT and disabling the sample loop)

**Comment by cmatsuoka** [comment]
Just to make sure we're in sync: I edited space.amf using OpenMPT, pattern 19, channel 3, rows 0-15 according to the following screenshot:

![image](https://cloud.githubusercontent.com/assets/317355/13206236/a4834004-d8d8-11e5-9636-789108e9414d.png)

This is the sound I get from libxmp 4.3.11 playing the same section (it's a zip because github doesn't like audio formats): 

[a.zip](https://github.com/cmatsuoka/libxmp/files/139924/a.zip)

This sample seems to be looping correctly for me. Am I checking the correct one?

**Comment by speachy** [comment]
Yes, you're looking at the same thing I am.  So this is quite strange. So here's what I'm hearing:

[bad-output.zip](https://github.com/cmatsuoka/libxmp/files/139934/bad-output.zip)

Generated with 'xmp -M "0,1,4,5,6,7" SPACE.AMF -s 1 -t 10 -d wav', freshly compiled from git HEAD.

**Comment by cmatsuoka** [comment]
Yes, that sounds very wrong! But it's also quite different from my output using the same command:

[good-output.zip](https://github.com/cmatsuoka/libxmp/files/139935/good-output.zip)

What compiler/version are you using to build the code? Also it could be interesting to re-clone the repository in a different location and retest to rule out old object files. My development environment is mostly Fedora 23 and Mac OS  X, but if you're using something different I can try to replicate the environment to see if I can reproduce the problem.

**Comment by speachy** [comment]
Well, blowing away my entire working tree (originally cloned in April 2013), cloning and compiling anew looks like it solved the problem.  It's strange how 'make clean' didn't clean this up properly.

Sorry to have wasted everyone's time (mine included!) on this wild goose chase.

**Comment by cmatsuoka** [comment]
So maybe we have a bug in the clean target. I'll check that and fix if I find something.
