### ISSUE TITLE
[Bug] when loads 256 patterns chiptune made with FT2, xmp crashes.

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#52]
http://modarchive.org/index.php?request=view_by_moduleid&query=42170
when I load this big chiptune witch has 256 patterns, it crashes.
Normal Tracker will load fine (confirmed with Schism,Milky,OpenMPT)

EDIT: Oops. Looks like I misstyped

**Comment by cmatsuoka** [comment]
It doesn't crash in my test, but it doesn't play either. This is probably caused by the Scream Tracker 0xfe/0xff marker. Fixing.

**Comment by cmatsuoka** [comment]
Marker pattern parsing fixed. It now plays the module (with total time of 30min 6s instead of 31min 7s listed in the instrument text). I'm not sure what could be causing the one minute difference.

    Loading finalchp.xm (1 of 1)
    Module name  : dreamchip megamix II
    Module type  : FastTracker v2.00 XM 1.04
    Module length: 255 patterns
    Patterns     : 256
    Instruments  : 102
    Samples      : 9
    Channels     : 14 [ 8 8 8 8 8 8 8 8 8 8 8 8 8 8 ]
    Duration     : 30min06s
    Speed[0F] BPM[4A] Pos[FE/FE] Pat[B0/FF] Row[7F/7F] Chn[0E/0E]      0:30:05.3

**Comment by cmatsuoka** [comment]
Milkytracker also plays this module in 30min and a few seconds, so I'll assume it's correct until someone finds a specific timing bug.
