### ISSUE TITLE
[Future Request] Fix INSTALL file

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#53]
There is no ./configure, so not compiling. I assume i need to use autoconf first.
So can you fix INSTALL document?

**Comment by cmatsuoka** [comment]
There's no configure in the git repository because it's a generated file, but there is a configure file in the distribution package, see https://sourceforge.net/projects/xmp/files/libxmp/4.3.12/. The INSTALL file is intended to the general non-developer audience that use the distribution tarball.

    $ tar tvf libxmp-4.3.12.tar.gz | grep configure
    -rw-rw-r-- claudio/claudio  3108 2016-02-28 20:29 libxmp-4.3.12/configure.ac
    -rwxrwxr-x claudio/claudio 151871 2016-02-09 09:19 libxmp-4.3.12/configure
