### ISSUE TITLE
[Future Request] Fix Changelog

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#54]
in version 4.3.11, Time is wrong. it will be 20160306.

**Comment by cmatsuoka** [comment]
Actually 4.3.11 was released in 20160212. If you refer to 4.3.12 being 20160305 instead of 20160306, the release candidate tarball was generated in the previous day :)

**Comment by cmatsuoka** [comment]
Ah, I got it. It said 2015. Ok, fixing!
