### ISSUE TITLE
[bug] when plays bz_fil.it, it is unable to play

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#57]
see title. 
http://modarchive.org/index.php?request=view_by_moduleid&query=39657
this tune is unable to play in xmp for android.

**Comment by knight-ryu12** [comment]
using Android 4.4.2 Kitkat.

**Comment by knight-ryu12** [comment]
also, sorry for too many bug report!

**Comment by knight-ryu12** [comment]
It is my side problem. I think I got a bad file.

**Comment by cmatsuoka** [comment]
We love bug reports. I'll check it anyway.

**Comment by cmatsuoka** [comment]
Probably a bad file. It played correctly in my test builds.

**Comment by knight-ryu12** [comment]
Yeah. I got it. it was bad file :3
2016/05/24 6:18 "Claudio Matsuoka" <notifications@github.com>:
