### ISSUE TITLE
Add support for Amiga filter on/off

### ISSUE THREAD

**Issue by cmatsuoka** [cmatsuoka/libxmp#58]
Libxmp 4.4 adds support for a mixer modeled after the Amiga 500 sound output. This allows the led filter to be implemented in a convincing way. Add this issue as a reminder to do so before the release. Also, if possible, we'd like to test it with a real module and compare the sound output to that from a real Amiga.

**Comment by cmatsuoka** [comment]
@sagamusix, do you have a test case for Protracker effect E0?

**Comment by sagamusix** [comment]
No, OpenMPT doesn't implement any Amiga filter stuff.

**Comment by cmatsuoka** [comment]
Led filter implemented using the A500 modeling mixer. This is an optional mixer available for Amiga modules. It uses about 3x more CPU and, with my headphones, it isn't that different from the standard mixer. Oldskool purists can enable it in the command-line player.
