### ISSUE TITLE
669 peculiarities

### ISSUE THREAD

**Issue by sagamusix** [cmatsuoka/libxmp#61]
Today I did some digging regarding the 669 format, and here are some findings that are also relevant to xmp:

- xmp discards any pattern effects (apart from speed commands) on rows where no instrument number is placed. I'm not sure where you got this information, but all pattern commands apart from tone portamento (c) can be triggered on any row.
- Like most other oldskool trackers, Composer 669 does not have linear frequency slides. **However**, unlike all those other trackers, Composer 669 uses frequencies rather than periods internally! So portamento adds a fixed amount of Hz rather than periods, and is more effective in the lower octaves than in the higher octaves (the opposite is true for other oldskool formats).
- Portamentos (a/b) are executed on every tick, and add (value * 80) Hz to the current frequency.
- Similarly, Tone Portamento (c) is executed on every tick but adds (value * 40) Hz.
- The Finetune command (d) adds (value * 80) Hz to the frequency. If there are several consecutive finetune commands for the same note, they override each other's effect.
- "Vibrato" (e) adds (value * 669) Hz on every other tick.

**Comment by sagamusix** [comment]
Oh, and once you get the Finetune command right, you can also set the initial tempo to the more correct 78 rather than 76 ("adjusted using Flux/sober.669").

**Comment by knight-ryu12** [comment]
so It means, 669 is Vibrato :P

**Comment by leilei-** [comment]
The first bullet soudns similar to #59 which was solved on .mod.  Does it still occur on the latest?

**Comment by sagamusix** [comment]
The commands are discarded right in the 669 loader, so it's unrelated.

**Comment by cmatsuoka** [comment]
Oh, that's interesting information. 669 support is probably one of that things that were placed into the code, worked once on a limited number of test modules, and were never touched again. Fixing for the next release. (There are other formats in this situation, and those hopelessly broken will be dropped so we can focus on quality.)

**Comment by sagamusix** [comment]
Yeah, I don't think _anyone_ really ever bothered understanding 669 thoroughly, which is probably why everyone just enabled linear slide mode and then treats them like "normal" modules.

**Comment by cmatsuoka** [comment]
Ok, most of the frequency-based "period" support implemented. Could you confirm the 40, 80 multipliers for the pitch slide effect parameters? They look a bit steep for Hz values if you consider A=440, or is it using a different frequency base?

**Comment by sagamusix** [comment]
What does that have to do with A440? The middle-C frequency is 8363 Hz, and the slides seem to slide a "reasonable" amount in the middle-C octave and one octave above.

**Comment by cmatsuoka** [comment]
Ah right, ok, everything was so strange in using frequencies that I thought they could have used an arbitrary value for frequencies as well.

**Comment by sagamusix** [comment]
Well, the only strange part is that they don't use linear frequency slides. :) After all, formats like S3M and IT also use frequencies rather than period, and they are never relative to A440 or anything, but simply are sampling rates.

**Comment by cmatsuoka** [comment]
Ah yeah, I think I was just confused by the "everything here is strange" sensation surrounding 669 :)

**Comment by cmatsuoka** [comment]
Pitch slide issues addressed. Sober.669 tempo and tuning match Compser 669 running on dosbox.
