### ISSUE TITLE
MDL peculiarities

### ISSUE THREAD

**Issue by sagamusix** [cmatsuoka/libxmp#64]
More frequency trouble!
After the discovery of how frequency slides work in 669, I present some new findings about the MDL format: Frequency slides are not linear, but they are also independent of the middle-C frequency.
Regardless of what the middle-C frequency is, portamentos and vibratos behave as if the middle-C frequency was 8363 Hz (i.e. like normal Amiga slides). I've attached an [example](https://github.com/cmatsuoka/libxmp/files/368162/PERIOD.zip) which can be tried in Digitrakker 3 (runs fine in DOSBox).
The easiest way to solve this is probably to just ignore the middle-C frequency when translating into periods, and then actually use the middle-C frequency when translating back to frequency/increment values.

**Comment by cmatsuoka** [comment]
Additionally, it seems that MDL 1.1 keeps the middle-C frequency, but MDL 0.0 transposes the instrument in the usual way.

**Comment by sagamusix** [comment]
I tried figuring out what DigiTracker 2.0-2.2 would do (and MDL 0.0 files seem to be rather rare), but I couldn't get it to run in DOSBox (it wouldn't find the GUS). Do you know how to get it to run in DOSBox, before I power up my GUS machine? :)

**Comment by cmatsuoka** [comment]
I have only one MDL 0.0, "Breaking the Walls" (it's in the development regression tests directory, test-dev/data/m/breaking.mdl). No luck with old Digitrakker in DOSBox in my first attempt, I'll try it again at home with more time.

**Comment by mldoering** [comment]
hmmh,

don't know what version, I have a file called mechanic.mdl

any help



---
Digital unterschrieben mit GNU Privacy Guard
Fingerabdruck: 330F 99EE 65A7 DF35 BF20  B5DC A0DC 8F02 5B1E CC24

**Comment by cmatsuoka** [comment]
That should probably be "Mechanical and Supernaddy". My copy is MDL 1.1:
```
Loading mechanic.mdl (1 of 1)
Module name  : Mechanical And Supernaddy
Module type  : Digitrakker MDL 1.1
```

**Comment by sagamusix** [comment]
mechanic.mdl is an example song for DigiTrakker 3, so of course there is no MDL 0.x version available of that.

**Comment by cmatsuoka** [comment]
My previous report regarding MDL 0.0 doesn't make sense in the context of keeping the middle C for slides (i.e. it shouldn't produce the problems I'm experiencing here). I probably have a different bug elsewhere that's causing the problem with MDL 0.0.

**Comment by sagamusix** [comment]
The only effects which should be affected in the module you posted are the vibrato commands anyway, and while admittedly they sound rather strong (in libopenmpt), Digitrakker 3 plays them the same way. So in case you're  not referring to those vibrato commands, then indeed the fault must lie somewhere else.

**Comment by cmatsuoka** [comment]
Indeed it was a problem in the 0.0 sample chunk loader. It now plays correctly in both versions.
