### ISSUE TITLE
Hang in MDL loader

### ISSUE THREAD

**Issue by sagamusix** [cmatsuoka/libxmp#65]
Here's a test case that [afl](http://lcamtuf.coredump.cx/afl/) crashed libopenmpt with a while ago. I just threw my test cases at libxmp to see if any are also applicable to your library, and I've found one which seems to result in an infinite loop. I didn't check it with the most recent version of libxmp, but I don't think that any relevant changes have been made in the meantime.

[test.zip](https://github.com/cmatsuoka/libxmp/files/368182/test.zip)

**Comment by cmatsuoka** [comment]
Added a sanity check to detect the condition that causes the infinite loop and return an error instead.
