### ISSUE TITLE
MASI bugs

### ISSUE THREAD

**Issue by sagamusix** [cmatsuoka/libxmp#69]
The comments in the MASI loader suggested that you had trouble with getting the Sinaria music to play correctly, so I took a listen and see if that is really still the case.
There seems to be a lot of unneccessary guesswork in the sample loader: For example, there is no need to subtract two from the sample length. The sample header is laid out slightly differently compared to "normal" sample headers, but what it has in common with them is that it the header size is 96 bytes in both cases. As a result, for "normal" PSMs, you have a couple of leading silence bytes (as there are actually 19 padding bytes after the sample rate, not 16), and in the case of Sinaria PSMs, you miss the first two sample points, resulting in those distorted samples.
You also seem to be ignoring the flags (first field of the header), which should indicate that the sample is looped if the highest bit is set.

While we're at it, "get_song_2" will probably work for most real-world PSMs, but it oversimplifies the handling of the order list a bit for my taste (merging several opcodes into one, e.g. opcode 7 and 8). Feel free to look at my implementation for a better understanding how the OPLH chunk actually works.

**Comment by cmatsuoka** [comment]
Oh wow, I see what you mean. That OPLH chunk is really more complicated than it should be. Fixing.

**Comment by cmatsuoka** [comment]
Subchunks and sub-subchunk parsing implemented. Format support should be better now, but a few Sinaria songs (e.g. song10.psm) still sound quite ugly.

**Comment by cmatsuoka** [comment]
Also added handling of missing commands. I'm still unsure about Sinaria finetunes but I'll be fixed later (tm) when I compare the replayer output to actual game playback (Epictest play.exe doesn't seem to work with Sinaria modules).
