### ISSUE TITLE
[Android] when plays any tune, sound is buzzes and it can hurt my(someones) ear.

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#71]
Read title. 
This is serious issue. 
All my issue posted, Xperia Z2 Tablet. Android 4.4.2

**Comment by knight-ryu12** [comment]
Also, It can be any Android, or just myself. Idk

**Comment by cmatsuoka** [comment]
Can't reproduce the problem here. Would it be possible for you to record a video of the problem happening on your device?

**Comment by knight-ryu12** [comment]
Ok. I'll try.

2016/08/09 1:18 "Claudio Matsuoka" <notifications@github.com>:

**Comment by knight-ryu12** [comment]
Sorry, I figuared out problem, Low Buffering...

**Comment by cmatsuoka** [comment]
Did you change the default, or was it failing with the default buffer value?

**Comment by knight-ryu12** [comment]
Both. Also buzzing can be clear for load tunes
