### ISSUE TITLE
Conflicting types for 'clock'

### ISSUE THREAD

**Issue by fcambus** [cmatsuoka/libxmp#73]
When trying to compile libxmp on my system (OpenBSD) using the latest release tarball (4.4.0), I'm getting the following error:

```
src/mix_paula.c:67: error: conflicting types for 'clock'
/usr/include/time.h:127: error: previous declaration of 'clock' was here
gmake: *** [Makefile:66: src/mix_paula.lo] Error 1
```

Renaming `clock` to something like `paula_clock` solves the issue.

**Comment by cmatsuoka** [comment]
Renamed `clock()` to `do_clock()` (commit a608de9).

**Comment by fcambus** [comment]
Thanks!
