### ISSUE TITLE
configure file is missing

### ISSUE THREAD

**Issue by raidho36** [cmatsuoka/libxmp#78]
It's impossible to ./configure the project because the file is missing from the tree.

The "configure" is explicitly included in gitignore file, that may be the issue.

**Comment by knight-ryu12** [comment]
try using autoconf.

**Comment by cmatsuoka** [comment]
It's a generated file and thus intentionally excluded from the repository. As Ryu said, generate yours using autoconf. The configure script is included in the distribution package.
