### ISSUE TITLE
[Enhancement] AUR Repo of libxmp

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#79]
I use Archlinux, so I found libxmp and xmp repo in AUR.
ongoing release version maintained by grimi https://aur.archlinux.org/packages/libxmp/
git version (may unstable) maintained by myself https://aur.archlinux.org/packages/libxmp-git/ (who use this..)

**Comment by cmatsuoka** [comment]
Thanks for the collaboration and effort.
