### ISSUE TITLE
src/loaders/prowizard/np2.c(77): Comparison result always 0

### ISSUE THREAD

**Issue by sezero** [cmatsuoka/libxmp#85]
Warning from OpenWatcom 1.9:
src/loaders/prowizard/np2.c(77): Warning! W124: Comparison result always 0

Some gcc version emit a similar warning, some gcc versions don't warn at all
while optimizing away the check.

The problem is, the resulting ptable[i] value cannot be greater than 255
because it is an unsigned char, but if the intention is to check the value
before storing in ptable[i] then the check is wrong and is not working.

**Comment by sezero** [comment]
There is another warning from src/depackers/unlzx.c line 882, i.e.
`	if (decr->decrunch_length <= 0)`
decrunch_length is unsigned: if the intention is to check if it accidentally
wrapped around, then it must be changed to signed.

**Comment by cmatsuoka** [comment]
Removed the first test, and changed decr->decrunch_length type to signed.
