### ISSUE TITLE
Samples corrupted in fracture.stm and other STM modules

### ISSUE THREAD

**Issue by viiri** [cmatsuoka/libxmp#92]
https://github.com/cmatsuoka/libxmp/blob/master/test-dev/data/m/fracture.stm

**Comment by viiri** [comment]
[stm.zip](https://github.com/cmatsuoka/libxmp/files/770168/stm.zip)
More samples attached.

**Comment by sezero** [comment]
I think this is fixed by commit ca11190066 (#93). Closing.
